#![cfg_attr(not(test), no_std)]

pub mod adsr;
pub mod amp_adder;
pub mod amp_mixer;
pub mod bass;
pub mod cello;
pub mod choir;
pub mod double_oscillator;
pub mod electric_piano;
pub mod filter;
pub mod free_list;
pub mod french_horn;
pub mod guitar_acoustic;
pub mod instrument_template_basic;
pub mod lfo_amplitude;
pub mod midi;
pub mod midi_channels;
pub mod midi_events;
pub mod midi_notes;
pub mod midi_time;
pub mod midi_track;
pub mod note;
pub mod oscillator;
pub mod piano;
pub mod sax;
pub mod silence;
pub mod sound_sample;
pub mod sound_source_core;
pub mod steady_one;
pub mod violin;
mod wave_tables;
