[package]
name = "entertainer"
version = "0.1.0"
edition = "2024"

[dependencies]

portaudio = { version = "0.8.0" }
midly = { version = "0.5.3", default-features = false }
midi-nostd = {path = "../../midi-nostd" }

[profile.release]
debug = true # This will include debug info

